/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "AddDevice": {                                   "en": "Add #-Button to add device",                      "de": "Zum Hinzufügen +-Button betätigen",               "ru": "Добавить # -Кнопка для добавления устройства",    "pt": "Adicione # -Button para adicionar dispositivo",   "nl": "Voeg # -knop toe om apparaat toe te voegen",      "fr": "Ajouter un bouton # pour ajouter un périphérique", "it": "Aggiungere #-Pulsante per aggiungere il dispositivo", "es": "Agregar #-Botón para agregar el dispositivo",     "pl": "Dodaj #-przycisk, aby dodać urządzenie",          "zh-cn": "添加#-添加装置"},
    "Cannot find any device": {                      "en": "Cannot find new devices",                         "de": "Kein neues Gerät gefunden",                       "ru": "Не могу найти новые устройства",                  "pt": "Não é possível encontrar novos dispositivos",     "nl": "Kan geen nieuwe apparaten vinden",                "fr": "Impossible de trouver de nouveaux appareils",     "it": "Non riesce a trovare nuovi dispositivi",          "es": "No se puede encontrar nuevos dispositivos",       "pl": "Nie mogę znaleźć nowych urządzeń",                "zh-cn": "无法找到新的设备"},
    "Enable adapter first": {                        "en": "Enable adapter first",                            "de": "Adapter nicht aktiv. Adapter aktivieren",         "ru": "Сначала включите адаптер",                        "pt": "Ativar o adaptador primeiro",                     "nl": "Schakel eerst de adapter in",                     "fr": "Activer d'abord l'adaptateur",                    "it": "Attivare prima l'adattatore",                     "es": "Habilitar el adaptador de primera",               "pl": "Włączyć zasilacz pierwszy",                       "zh-cn": "第一个启用适配器"},
    "Find a device": {                               "en": "Find a device",                                   "de": "Gerät suchen",                                    "ru": "Найти устройство",                                "pt": "Encontre um dispositivo",                         "nl": "Zoek een apparaat",                               "fr": "Trouver un appareil",                             "it": "Trovare un dispositivo",                          "es": "Encontrar un dispositivo de",                     "pl": "Znaleźć urządzenie",                              "zh-cn": "找到一个设备"},
    "Please wait, looking for devices...": {         "en": "Please wait...",                                  "de": "Bitte warten...",                                 "ru": "Пожалуйста, подождите...",                        "pt": "Por favor, espere...",                            "nl": "Even geduld aub...",                              "fr": "S'il vous plaît, attendez...",                    "it": "Si prega di attendere...",                        "es": "Por favor, espere...",                            "pl": "Proszę czekać...",                                "zh-cn": "请等等..."},
    "Select a device": {                             "en": "Select a device",                                 "de": "Geräte auswählen",                                "ru": "Выберите устройство",                             "pt": "Selecione um dispositivo",                        "nl": "Selecteer een apparaat",                          "fr": "Sélectionnez un appareil",                        "it": "Selezionare un dispositivo",                      "es": "Seleccione un dispositivo",                       "pl": "Wybierz urządzenie",                              "zh-cn": "选择一个设备"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Settings",                                        "pt": "Configurações",                                   "nl": "instellingen",                                    "fr": "Paramètres",                                      "it": "Impostazioni",                                    "es": "Configuración",                                   "pl": "Parametry",                                       "zh-cn": "设置"},
    "WiFi Light": {                                  "en": "WiFi Light",                                      "de": "WiFi Light Einstellungen",                        "ru": "Пример",                                          "pt": "WiFi Light",                                      "nl": "WiFi licht",                                      "fr": "Lumière WiFi",                                    "it": "WiFi Di Luce",                                    "es": "WiFi Luz",                                        "pl": "Bezprzewodowy Światło",                           "zh-cn": "无线光"},
    "devices": {                                     "en": "Dives list",                                      "de": "Geräte-liste",                                    "ru": "Список погружений",                               "pt": "Lista de mergulhos",                              "nl": "Duiklijst",                                       "fr": "Liste des plongées",                              "it": "Immersioni elenco",                               "es": "Lista de inmersiones",                            "pl": "Lista nurkowania ",                               "zh-cn": "潜列表"},
    "ip": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IK P",                                            "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IZ",                                              "zh-cn": "IP"},
    "looking for device": {                          "en": "Looking for devices",                             "de": "Suche Geräte",                                    "ru": "Ищем устройства",                                 "pt": "Procurando dispositivos",                         "nl": "Op zoek naar apparaten",                          "fr": "À la recherche d'appareils",                      "it": "Cerca dispositivi",                               "es": "Buscando dispositivos",                           "pl": "Szukam urządzeniach",                             "zh-cn": "在寻找的设备"},
    "name": {                                        "en": "Name",                                            "de": "Bezeichnung",                                     "ru": "имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Nazwa",                                           "zh-cn": "名称"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern der Einstellungen wird der Adapter automatisch neu gestartet.", "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями", "pt": "ao salvar o adaptador reinicia imediatamente com a nova configuração", "nl": "on save adapter wordt onmiddellijk opnieuw gestart met nieuwe configuratie", "fr": "sur save, l'adaptateur redémarre immédiatement avec la nouvelle configuration", "it": "salva adattatore riavvia con la nuova config immediatamente", "es": "en guardar adaptador se reinicia con la nueva config de inmediato", "pl": "zapisz ponownym uruchomieniu zasilacza z nowy konfig raz", "zh-cn": "在保存适配器重新启动与新的配置立即"},
    "pollIntervall": {                               "en": "Poll Intervall",                                  "de": "Pollintervall",                                   "ru": "Опрос Интервал",                                  "pt": "Poll Intervall",                                  "nl": "Poll Intervall",                                  "fr": "Sondage Intervall",                               "it": "Sondaggio Intervall",                             "es": "Intervalo De Poll",                               "pl": "Interwał Sondowania ",                            "zh-cn": "调查区间"},
    "port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "口"},
    "type": {                                        "en": "Type",                                            "de": "Typ",                                             "ru": "Тип",                                             "pt": "Tipo",                                            "nl": "Type",                                            "fr": "Type",                                            "it": "Tipo",                                            "es": "Tipo de",                                         "pl": "Typ",                                             "zh-cn": "类型"},
};