/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "AddDevice": {                                   "en": "Add #-Button to add device",                      "de": "Zum Hinzufügen +-Button betätigen",               "ru": "Добавить # -Кнопка для добавления устройства",    "pt": "Adicione # -Button para adicionar dispositivo",   "nl": "Voeg # -knop toe om apparaat toe te voegen",      "fr": "Ajouter un bouton # pour ajouter un périphérique"},
    "Cannot find any device": {                      "en": "Cannot find new devices",                         "de": "Kein neues Gerät gefunden",                       "ru": "Не могу найти новые устройства",                  "pt": "Não é possível encontrar novos dispositivos",     "nl": "Kan geen nieuwe apparaten vinden",                "fr": "Impossible de trouver de nouveaux appareils"},
    "Enable adapter first": {                        "en": "Enable adapter first",                            "de": "Adapter nicht aktiv. Adapter aktivieren",         "ru": "Сначала включите адаптер",                        "pt": "Ativar o adaptador primeiro",                     "nl": "Schakel eerst de adapter in",                     "fr": "Activer d'abord l'adaptateur"},
    "Find a device": {                               "en": "Find a device",                                   "de": "Gerät suchen",                                    "ru": "Найти устройство",                                "pt": "Encontre um dispositivo",                         "nl": "Zoek een apparaat",                               "fr": "Trouver un appareil"},
    "Please wait, looking for devices...": {         "en": "Please wait...",                                  "de": "Bitte warten...",                                 "ru": "Пожалуйста, подождите...",                        "pt": "Por favor, espere...",                            "nl": "Even geduld aub...",                              "fr": "S'il vous plaît, attendez..."},
    "Select a device": {                             "en": "Select a device",                                 "de": "Geräte auswählen",                                "ru": "Выберите устройство",                             "pt": "Selecione um dispositivo",                        "nl": "Selecteer een apparaat",                          "fr": "Sélectionnez un appareil"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Settings",                                        "pt": "Configurações",                                   "nl": "instellingen",                                    "fr": "Paramètres"},
    "WiFi Light": {                                  "en": "WiFi Light",                                      "de": "WiFi Light Einstellungen",                        "ru": "Пример",                                          "pt": "WiFi Light",                                      "nl": "WiFi licht",                                      "fr": "Lumière WiFi"},
    "devices": {                                     "en": "Dives list",                                      "de": "Geräte-liste",                                    "ru": "Список погружений",                               "pt": "Lista de mergulhos",                              "nl": "Duiklijst",                                       "fr": "Liste des plongées"},
    "ip": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IK P",                                            "fr": "IP"},
    "looking for device": {                          "en": "Looking for devices",                             "de": "Suche Geräte",                                    "ru": "Ищем устройства",                                 "pt": "Procurando dispositivos",                         "nl": "Op zoek naar apparaten",                          "fr": "À la recherche d'appareils"},
    "name": {                                        "en": "Name",                                            "de": "Bezeichnung",                                     "ru": "имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern der Einstellungen wird der Adapter automatisch neu gestartet.", "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями", "pt": "ao salvar o adaptador reinicia imediatamente com a nova configuração", "nl": "on save adapter wordt onmiddellijk opnieuw gestart met nieuwe configuratie", "fr": "sur save, l'adaptateur redémarre immédiatement avec la nouvelle configuration"},
    "pollIntervall": {                               "en": "Poll Intervall",                                  "de": "Pollintervall",                                   "ru": "Опрос Интервал",                                  "pt": "Poll Intervall",                                  "nl": "Poll Intervall",                                  "fr": "Sondage Intervall"},
    "port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port"},
    "type": {                                        "en": "Type",                                            "de": "Typ",                                             "ru": "Тип",                                             "pt": "Tipo",                                            "nl": "Type",                                            "fr": "Type"},
};